spring.application.name=commitment-admin-api
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/commitment_app}
spring.data.mongodb.database=${MONGODB_DATABASE:commitment_app}
spring.data.mongodb.auto-index-creation=true
server.port=${SERVER_PORT:8080}
app.cors.allowed-origin-patterns=${CORS_ALLOWED_ORIGIN_PATTERNS:http://localhost:[*],http://127.0.0.1:[*]}